# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-06 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftpcredential',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
